// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-4Y04djYtls33LsXh7DBiMi8mftxMN2Y',
    appId: '1:268676212175:web:8ced2191e1f53304a5deba',
    messagingSenderId: '268676212175',
    projectId: 'mtubilgimobil',
    authDomain: 'mtubilgimobil.firebaseapp.com',
    storageBucket: 'mtubilgimobil.firebasestorage.app',
    measurementId: 'G-GSBQYCWX3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZc-kaXMntP9pvfxAUyLSMdGIejKtjlV4',
    appId: '1:268676212175:android:538eaadf8f4a488ba5deba',
    messagingSenderId: '268676212175',
    projectId: 'mtubilgimobil',
    storageBucket: 'mtubilgimobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjl08f9c8FERnDBY_X9a02UCjYGsReKFU',
    appId: '1:268676212175:ios:eb687e555507650ba5deba',
    messagingSenderId: '268676212175',
    projectId: 'mtubilgimobil',
    storageBucket: 'mtubilgimobil.firebasestorage.app',
    iosBundleId: 'com.example.mtubilgimobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjl08f9c8FERnDBY_X9a02UCjYGsReKFU',
    appId: '1:268676212175:ios:eb687e555507650ba5deba',
    messagingSenderId: '268676212175',
    projectId: 'mtubilgimobil',
    storageBucket: 'mtubilgimobil.firebasestorage.app',
    iosBundleId: 'com.example.mtubilgimobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-4Y04djYtls33LsXh7DBiMi8mftxMN2Y',
    appId: '1:268676212175:web:cd0d4512e4e3661ea5deba',
    messagingSenderId: '268676212175',
    projectId: 'mtubilgimobil',
    authDomain: 'mtubilgimobil.firebaseapp.com',
    storageBucket: 'mtubilgimobil.firebasestorage.app',
    measurementId: 'G-T66758CQMW',
  );
}
